# Generated by Django 2.0.5 on 2019-10-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('job_id', models.CharField(max_length=256, verbose_name='任务id')),
                ('name', models.CharField(max_length=64, verbose_name='job名称')),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'running'), (2, 'finish')], verbose_name='job状态')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'job信息表',
                'db_table': 'job_info',
            },
        ),
    ]
