# Generated by Django 2.0.5 on 2019-10-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='用户id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'running'), (2, 'finish')], default=0, verbose_name='job状态'),
        ),
    ]
